<template>
    <img src="@/assets/banner-example.png" alt="">
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
    <p class="font-light">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolore earum aliquid nemo consectetur sint enim, pariatur animi necessitatibus laborum optio non totam accusantium, itaque temporibus nobis, omnis repellendus nisi? Vel!</p>
</template>

<style>
</style>

<script>
    export default {
        mounted() {
            // SET PAGE TITLE
            document.title = "Beranda - SMK MUHAMMADIYAH KAJEN";  
        },
    }
</script>